/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pedho' at '28/12/16 20:44' with Gradle 2.14.1
 *
 * @author pedho, @date 28/12/16 20:44
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
